from typing import List, TypedDict

from graph.ingest import RAGVectorStore


class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        question(str): string representing the question.
        answer(str): answer generated by the LLM
        web_search(bool): whether to add search
        documents(List[str]): list of documents to be used for answer generation
    """

    question: str
    answer: str
    web_search: bool
    documents: List[str]
    retriever: RAGVectorStore